### ISSUE TITLE
CSS parse error: extra closing bracket

### ISSUE THREAD

**Issue by geoffreyrichey** [jhildenbiddle/css-vars-ponyfill#104]
This issue popped up with an icon font that I have included in my CSS. What trips it up is a single class that has "\\\\" set as the content of a pseudo-selector. After further testing I can reproduce the issue like this:

```css
.icon-breaking-class:before {
    content: "\\"
}

.class-to-ponyfill {
    color: var(--blue);
}
```

I couldn't quite identify the regex pattern that causes this to throw an error and I've subsequently fixed it by changing the character in my font builder but wanted to document this for any others who might/have run into this specific issue.

FYI...great plugin. I'm using it not only for legacy browser support but for easily applying custom themes for each of our clients. Thanks for building this!
