### ISSUE TITLE
 how can i change the --color with the click event?

### ISSUE THREAD

**Issue by quang-sunlight** [jhildenbiddle/css-vars-ponyfill#105]

**Comment by jhildenbiddle** [comment]
CSS:

```css
:root {
  --color: red;
}

body {
  background-color: var(--color);
}
```

HTML:

```html
<button id="change-color">Change Color</button>
```

JS:

```js
// Initialize ponyfill (sets background to red)
cssVars({
  // Options...
});

// Change color on button click (sets background to green)
document.querySelector('#change-color').addEventListener('click', function(evt) {
  cssVars({
    variables: {
      '--color': 'green';
    }
  });
});
```

Link: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
