### ISSUE TITLE
Variables from selector and selector with :before are merged

### ISSUE THREAD

**Issue by justinrlle** [jhildenbiddle/css-vars-ponyfill#133]
I've got some html which looks more or less like this:
```html
<span class="switch">
  <span class="slider"></span>
</span>
```
```css
:root {
  --color-red: red;
  --color-blue: blue;
}

.switch {
  position: relative;
  display: inline-block;
  width: 36px;
  height: 20px;
}
.slider {
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  border-radius: 34px;
  background-color: var(--color-red);
}

.slider:before {
  position: absolute;
  content: '';
  height: 16px;
  width: 16px;
  right: 2px;
  bottom: 2px;
  border-radius: 50%;
  background-color: var(--color-blue);
}
```
which gives a red slider with a blue dot (<https://jsfiddle.net/qj269ucp>).

But on IE, the whole slider is blue, and I have this in the devtools (this is an angular application, so there is a lot of `[__ng-content]` in the selectors): 
![image](https://user-images.githubusercontent.com/10925994/88187631-11ac6600-cc37-11ea-9605-f9e3f11b59a3.png)
Values of CSS variables:
![image](https://user-images.githubusercontent.com/10925994/88187718-2b4dad80-cc37-11ea-8426-37bd59e9e1c5.png)

In the image, you can see that the `.slider::before` has `--primary-color` as background, the `.slider` has `--secondary-color-30`, which means that the slider should be `rgba(255, 0, 0, 0.3)`, and the `.slider:before` should be `#0000ff`.
But as you can see in the first screenshot, the `.slider` is `#0000ff`, just like the `.slider:before`.
