### ISSUE TITLE
Can I use Descendant selector with :root?

### ISSUE THREAD

**Issue by 617976080** [jhildenbiddle/css-vars-ponyfill#139]
I need to decide whether to switch CSS VAR to dark mode according to the open_dark property on the body. Can the CSS var Polyfill work：
```css
@media (prefers-color-scheme: dark) {
    :root body[open_dark="1"]{
       --text-color: red;
    }
}

```
