### ISSUE TITLE
Use data-xxx to the html ?

### ISSUE THREAD

**Issue by skyounet** [jhildenbiddle/css-vars-ponyfill#145]
Hello,

Thank you for this ponyfill.

I would like to run it with a `data-theme` element on the `html`. 
For example I have variables like this in my scss: 

```css
:root {
    --color-default: #383838;
    --color-primary: #C10022;
}
```

And i would like to change them if the `data-theme` is fill with this value for example : 

```css
:root[data-theme="S2"] {
    --color-default: #F9DC00;
    --color-primary: #F9DC00;
}
```

I've tried this in IE11, and the ponyfill don't apply the new color. Why ? Is that normal ?
(I also tried with a class, same "problem")
Thanks you.
