### ISSUE TITLE
Do vars only work under :root?

### ISSUE THREAD

**Issue by VicWei** [jhildenbiddle/css-vars-ponyfill#5]
Is this plugin support to set the vars under the class,
ex.
.test{
  --color; red;
}

**Comment by jhildenbiddle** [comment]
Vars must be defined as `:root`-level declarations.

This will work:

```css
:root {
  --a: red;
}

p {
  color: var(--a);
}
```

This will not work:

```css
p {
  --a: red;
  color: var(--a);
}
```

Creating a pony/polyfill to handle second scenario simply isn't possible.  Many discussions have been had on the topic:

* https://github.com/MoOx/postcss-cssnext/issues/99
* https://github.com/postcss/postcss-custom-properties/issues/1
* https://github.com/postcss/postcss-custom-properties/issues/9

Hence the `:root`-level limitation. 😄
