### ISSUE TITLE
IE11 print support

### ISSUE THREAD

**Issue by sheikalthaf** [jhildenbiddle/css-vars-ponyfill#52]
Whether this ponyfill support print in IE11?

**Comment by jhildenbiddle** [comment]
Yes.

The ponyfill doesn't affect printing. It allows CSS custom properties to be transformed to static values so the styles can be applied properly in legacy browsers.

For example:

```css
:root {
  --mycolor: red;
}

p {
  color: var(--mycolor);
}
```

Without the ponyfill, IE11 would not display`<p>` text as red because it doesn't understand CSS custom property values like `--mycolor: red` or functions like `var(--mycolor)`. The ponyfill transforms the above CSS to the following:

```css
p {
  color: red;
}
```

Now paragraph text will be red both on screen and when printed (assuming of course that your printer is configured to print color).
