### ISSUE TITLE
Media Query Support

### ISSUE THREAD

**Issue by mhemesath** [jhildenbiddle/css-vars-ponyfill#58]
Wondering if it's possible to honor media queries when outputting CSS. For example:

```css
@media only screen and (max-width: 600px) {
  :root {
    --color: red;
  }

  .foo {
    color: var(--color);
  }
}
```

would output
```html
<style>
@media only screen and (max-width: 600px) {
  .foo {
    color: red;
  }
}
</style>
```
