### ISSUE TITLE
cssVars(): CSS parse error: property missing ':'  

### ISSUE THREAD

**Issue by KhoaSydney** [jhildenbiddle/css-vars-ponyfill#63]
Hi @jhildenbiddle ,

I have issue with cssVars when running webpack in production mode. This enables optimization using OptimizeCSSAssetsPlugin. When optimization is turned on, I can see **cssVars(): CSS parse error: property missing ':'**  in the console.  Do you have any idea why?

Maybe due to the following content in the css:
`toast-success{background-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAADsSURBVEhLY2AYBfQMgf///3P8+/evAIgvA/FsIF+BavYDDWMBGroaSMMBiE8VC7AZDrIFaMFnii3AZTjUgsUUWUDA8OdAH6iQbQEhw4HyGsPEcKBXBIC4ARhex4G4BsjmweU1soIFaGg/WtoFZRIZdEvIMhxkCCjXIVsATV6gFGACs4Rsw0EGgIIH3QJYJgHSARQZDrWAB+jawzgs+Q2UO49D7jnRSRGoEFRILcdmEMWGI0cm0JJ2QpYA1RDvcmzJEWhABhD/pqrL0S0CWuABKgnRki9lLseS7g2AlqwHWQSKH4oKLrILpRGhEQCw2LiRUIa4lwAAAABJRU5ErkJggg==")!important}#toast-container>.toast-warning{background-image:url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGYSURBVEhL5ZSvTsNQFMbXZGICMYGYmJhAQIJAICYQPAACiSDB8AiICQQJT4CqQEwgJvYASAQCiZiYmJhAIBATCARJy+9rTsldd8sKu1M0+dLb057v6/lbq/2rK0mS/TRNj9cWNAKPYIJII7gIxCcQ51cvqID+GIEX8ASG4B1bK5gIZFeQfoJdEXOfgX4QAQg7kH2A65yQ87lyxb27sggkAzAuFhbbg1K2kgCkB1bVwyIR9m2L7PRPIhDUIXgGtyKw575yz3lTNs6X4JXnjV+LKM/m3MydnTbtOKIjtz6VhCBq4vSm3ncdrD2lk0VgUXSVKjVDJXJzijW1RQdsU7F77He8u68koNZTz8Oz5yGa6J3H3lZ0xYgXBK2QymlWWA+RWnYhskLBv2vmE+hBMCtbA7KX5drWyRT/2JsqZ2IvfB9Y4bWDNMFbJRFmC9E74SoS0CqulwjkC0+5bpcV1CZ8NMej4pjy0U+doDQsGyo1hzVJttIjhQ7GnBtRFN1UarUlH8F3xict+HY07rEzoUGPlWcjRFRr4/gChZgc3ZL2d8oAAAAASUVORK5CYII=")!important}`

As you can see above the **base64** does not follow by the :. This is just my guess.

cheers,
Khoa

**Comment by jhildenbiddle** [comment]
Hey @KhoaSydney.

It doesn't look like the CSS above is the issue. I copy/pasted it into a fork of the CodePen demo to see if I got the same error, and the ponyfill processed it just fine.

* https://codepen.io/anon/pen/pYaOxj

Your original message included a [link to an issue](https://github.com/webpack-contrib/purifycss-webpack/issues/89) on in the [purify-webpack](https://github.com/webpack-contrib/purifycss-webpack) repo, presumably because this library is used somewhere in the your configuration or by the OptimizeCSSAssetsPlugin).  That particular issue is closed, but the issue author opened up [a separate issue in the purify repo](https://github.com/purifycss/purifycss/issues/144) which may offer assistance.

If all else fails, you can use the CodePen demo linked above to try and isolate the CSS that is throwing the error. I would verify that your source CSS works okay with the ponyfill first (which it sounds like it does), then test the CSS generated by the OptimizeCSSAssetsPlugin.

In the meantime, I can make the ponyfill error more informative by including text before/after the error occurred, but I'm not sure when I'll be able to get to that.

Not the quick fix you were probably looking for, but hopefully this creates a path forward. If you're still having issues, let me know and we'll figure out next steps.

**Comment by KhoaSydney** [comment]
Hi @jhildenbiddle ,

Ponyfill works perfectly when css is not minimize. The issue only comes up in Test environment when minimize is turned on. I believe this has something to do with IE 11. The codepen above works perfectly in Chrome but it does not support running in IE and I believe this is where the issue is. I managed to debug the application and capture the screen with stacktrace where the error is thrown. 
![image](https://user-images.githubusercontent.com/3717031/54400693-2eb65800-4718-11e9-8197-779f8b1edb0b.png)


It fails when parsing this css https://ufile.io/it44t

Cheers,
Khoa

**Comment by jhildenbiddle** [comment]
@KhoaSydney --

The file you've linked to above is not valid CSS so I can't use it for testing.

What I have done in the meantime is create a basic demo that shows the ponyfill working properly with base64 images:

* https://stackblitz.com/edit/css-vars-ponyfill-63

To view in a IE11, load the preview (not the editor):

* https://css-vars-ponyfill-63.stackblitz.io/

I realize this demo isn't configured the same way as your app, but it provides a place to experiment with your CSS to try and isolate the issue. I've included the CSS from your original post, as well as a separate base64 image stored as a custom property value and applied via a `var()` function. All images appear as expected in both Chrome and IE11.

The point of all this is that it sounds like there is an issue somewhere within your production/optimization pipeline. I'm not ruling out a ponyfill issue, but the demo includes both minified and unminified versions of the same CSS, and both work without issue. This leads me to believe some other "optimization" is creating invalid CSS which the ponyfill cannot parse properly.

Another thing to try: Call the ponyfill with `onlyLegacy:true` and see if you get the same error in a modern browser. You should, since the ponyfill will generate the same CSS *unless* your optimizations include browser-specific CSS that the ponyfill cannot parse properly.

Hope this helps.

**Comment by KhoaSydney** [comment]
Hi @jhildenbiddle ,

I changed onlyLegacy = false then use Chrome to run the application. Now I can see the same error in chrome. I copied the css content from the stracktrace, pasted into codepen then run without any error in the console.  The same css is used in the application and codepen but there is only error in my application.

![image](https://user-images.githubusercontent.com/3717031/54412482-f24e2080-4746-11e9-9af9-3d6a9259f2bd.png)

**Comment by jhildenbiddle** [comment]
The fact that you see the same error in a modern browser with `onlyLegacy:false` is a good thing. This means it's not an IE-specific issue so it should be a bit easier to troubleshoot.

It looks like base64 resources are causing the issue. I see only three in the CSS used in your CodePen demo:

```css
@font-face {
    font-family: WebComponentsIcons;
    font-style: normal;
    font-weight: 400;
    src: url("data:font/ttf;base64, ... ") format("truetype");
}

.k-slider-horizontal .k-tick {
    background-image: url("data:image/gif;base64, ... ");
}

.k-slider-vertical .k-tick {
    background-image: url("data:image/gif;base64, ... ");
}
```

Here are a few steps we can take to try and isolate the issue:

1. Remove these `@font-face` and `background-image` declarations from your CSS. If the ponyfill is able to process the remaining CSS without issue, we know one-or-more of these declarations are the cause of the ponyfill parsing error.
1. Assuming the removal of the declarations above allows the ponyfill to work without issue, try reintroducing each declaration individually to see if *all* base64 resources are causing the issue or a specific one (for example, the `font/ttf` but not the `image/gif` resources).
1. Once the problematic declaration(s) are identified, try manually converting them to base64 and inserting them into your CSS (i.e. don't have webpack convert your `url(...)` values to base64--do it yourself). For the webfont, you can use [Font Squirrel's Webfont Generator](https://www.fontsquirrel.com/tools/webfont-generator) (select "Expert..." and the "CSS: Base64 Encode" option) and for the images you can use any online encode (like [this one](https://www.base64-image.de/)).

The steps above assume we're working around issues with base64 encoding. This may not be the case, but given the errors you've listed above it seems like a good place to start. If the errors aren't related to base64, then a similar process of isolating the CSS that is causing the issue needs to be taken. The goal is to identify the difference(s) between the development/unoptimized CSS that the ponyfill transforms without issue and the production/optimized CSS that causes the parsing error. Once we limit the CSS we're testing to something manageable (not *all* of the CSS in your app) we can figure out the best way to work around the issue.

**Comment by KhoaSydney** [comment]
Hi @jhildenbiddle.

I have identified the declaration that cause issue below:
` .k-slider-horizontal .k-tick {
       background-image: url("data:image/gif;base64,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7"); // url(map-get($data-uris, 'slider-h.gif'));
    }`

The image is manually converted to base64 using the link you sent above. The encoding content is exactly what we have if use with webpack. If I commented out the above css, it works again. I spent sometime debugging the code, especially in the parseCss function. It looks like to me the regex to extract the declaration somehow idententify base64 as the property. The content passed  into `parseCss` when this happened also looks strange e.g `,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7")}.k-colorpicker{width:auto;border-width:0;display:inline-block;position:relative;overflow:visible}.k-colorpicker .k-selected-color{padding:4px;width:calc(8px + 1.42857em);height:calc(8px + 1.42857em);box-sizing:border-box;line-height:0;position:relative;overflow:hidden}.k-colorpicker .k-selected-color .k-i-line{border-top:1px solid #f31700;width:200%;height:200%;position:absolute;top:50%;left:50%;transform:translate(-33%,-33%) rotate(45deg);transform-origin:0 0}.k-colorpicker .k-selected-color .k-i-line:before{display:none}.k-colorpicker `  

Each time I commented  out the ` .k-slider-horizontal .k-tick ` the application works again. 

The link below content css that contains the `k-slider-horizontal .k-tick`
https://ufile.io/6shb8
cheers,
Khoa

**Comment by jhildenbiddle** [comment]
Can you share the following:

1. The image file referenced in the `.k-slider-horizontal .k-tick { }` declaration that is causing the issue (the binary file, not the base64 text in a CSS file)
1. The unoptimized CSS that contains the above CSS rule that the ponyfill is able to process without issue.

This will allow me to try a few things on my end without the back-and-forth.

**Comment by KhoaSydney** [comment]
Hi @jhildenbiddle ,

Please have a look at the links for unminify css and original gif file:
https://ufile.io/flz2u
https://ufile.io/iez6r

I did some comparison on my side and pick up one difference between the original css and minify version:

**Original**
`.k-slider-horizontal .k-tick {
  background-image: url("data:image/gif;base64,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7");}` **<=== semicolon at the end** 

**Minify**
.k-slider-horizontal .k-tick{background-image:url("data:image/gif;base64,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7")}

As you can see from the original version, it has a semicolon at the end. Do you think this missing semicolon cause the regex to return a false result **e.g base64 property missing :**


Thanks for your help.

cheers,
Khoa

**Comment by jhildenbiddle** [comment]
Thanks for sharing the files, @KhoaSydney.

I've verified that the image-to-base64 conversion and minification of your CSS aren't the issue.

I noticed the `/* purgecss */` comments in your CSS so I assume you are using [purgecss](https://www.purgecss.com) as part of your CSS optimization. Based on the [PurgeCSS docs](https://www.purgecss.com/whitelisting#in-the-css-directly), it appears that start/end comments need to be paired properly:

```css
/* purgecss start ignore */
/* purgecss end ignore */

/* purgecss start ignore */
/* purgecss end ignore */

/* purgecss start ignore */
/* purgecss end ignore */
...
```

Looking at your CSS, I see that these comments are not paired properly. Here are the comments in the order that they appear in `blue-theme-usable.css`:

```css
/* purgecss start ignore */
/* purgecss start ignore */
/* purgecss start ignore */
/* purgecss end ignore */
/* purgecss start ignore */
/* purgecss end ignore */
/* purgecss start ignore */
/* purgecss end ignore */
/* purgecss end ignore */
/* purgecss end ignore */
```

There are an equal number of start/end comments, but they  appear to be nested:

```css
/* purgecss start ignore */
    /* purgecss start ignore */
        /* purgecss start ignore */
        /* purgecss end ignore */
        /* purgecss start ignore */
        /* purgecss end ignore */
        /* purgecss start ignore */
        /* purgecss end ignore */
    /* purgecss end ignore */
/* purgecss end ignore */
```

I don't believe nesting `/* purgecss */` comments is supported, which is very likely the cause of your issue. Update these comments and see if your issue is resolved. If not, try disabling purgecss entirely.

**Comment by KhoaSydney** [comment]
Hi @jhildenbiddle ,

The purgecss plugin were removed  when I added in css vars ponyfill to make it easier to isolate issues. The purgecss comments are from unminified version of the css which I havent remove yet and they work fine.  It is the minified version that causes issue.

cheers,
Khoa

**Comment by jhildenbiddle** [comment]
The `.k-slider-horizontal .k-tick` is not the issue. Here is a demo that includes both the original and minified version of the rules you've provided above:

* https://stackblitz.com/edit/css-vars-ponyfill-63-2?file=style.css

To view in a IE11, load the preview (not the editor):

* https://css-vars-ponyfill-63-2.stackblitz.io/

Works fine in modern and legacy browsers (Chrome + IE11).

What other items in your optimization pipeline can you disable? For example, can you disable the minifier or make its settings less aggressive? Are you using any other utilities like PurgeCSS that modify your CSS in ways other than simply minifying?

Apologies if it feels like we're going in circles. I just have yet to be provided with a block of CSS that causes the ponyfill to produce an error in IE11, so from my perspective all signs point to an issue somewhere in your production pipeline.

**Comment by KhoaSydney** [comment]
Hi @jhildenbiddle .

I really appreciated your helps on this. I managed to reproduce the error. Please have a look at the link below:
https://stackblitz.com/edit/css-vars-ponyfill-63-2-hanm17

Please expand the console in order to see the error in details.

cheers,
Khoa

**Comment by jhildenbiddle** [comment]
The demo helped.

The parsing error occurs:

1. When a rule containing a legacy IE `filter` value with quotes...

   ```css
   .sidepane-row.attachment:hover{background-image:linear-gradient(180deg,#eee 0,#fbfbfb);background-repeat:repeat-x;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="rgba(255, 238, 238, 0.93333)",endColorstr="rgba(255, 251, 251, 0.98431)",GradientType=0)}
   ```

1. ... and a rule with a base64 image...

   ```css
   .k-slider-horizontal .k-tick{background-image:url("data:image/gif;base64,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7")}
   ```

1. ... share the same quote style (single or double)...

   ```css
   /* Double quotes */
   .foo {
     filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="rgba(255, 238, 238, 0.93333)",endColorstr="rgba(255, 251, 251, 0.98431)",GradientType=0)
   }
   .bar {
     background-image:url("data:image/gif;base64,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7")
   }
   ```

   ```css
   /* Single quotes */
   .foo {
     filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='rgba(255, 238, 238, 0.93333)',endColorstr="rgba(255, 251, 251, 0.98431)",GradientType=0)
   }
   .bar {
     background-image:url('data:image/gif;base64,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7')
   }
   ```

1. ... are joined on the same line (typically through minification):

   ```css
   .foo{...}.bar{...}
   ```

Remember, after minification all CSS is reduced to a single line it doesn't matter where the rules are located. In your particular scenario, these three rules cause the error:

```css
/* This rule contains a var() function which prevents the parser from skipping the CSS block  */ 
.file-attach-bar{font-size:16px;color:var(--brand-info);height:32px;background-color:var(--brand-info-lighten-48-saturate-31);padding:5px 0;border-bottom:1px solid #f3f3f3;text-align:center}

/* This rule contains a legacy IE filter value with double-quoted values */
.sidepane-row.attachment:hover{background-image:linear-gradient(180deg,#eee 0,#fbfbfb);background-repeat:repeat-x;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="rgba(255, 238, 238, 0.93333)",endColorstr="rgba(255, 251, 251, 0.98431)",GradientType=0)}

/* This rule contains a double-quoted base64 image */
.k-slider-horizontal .k-tick{background-image:url("data:image/gif;base64,R0lGODlhAQC0AIABALi4uAAAACH5BAEAAAEALAAAAAABALQAAAIWjIGJxqzazlux2ovlzND2rAHgSIZWAQA7")}
```

Fortunately, there are multiple ways to address the issue:

1. Remove legacy IE `filter` declarations. 

   IE filters are notoriously slow and can introduce IE-specific layout bugs. Unless you absolutely need to support IE < 10, consider dropping support legacy IE. If you must support IE < 10, consider removing the legacy `filter` declarations and just use a background color as a fallback.

1. Fix your `filter` declarations

   I'm guessing you aren't testing with IE < 10 because your gradient rules won't render properly as currently defined. Specifically, legacy IE `filter` rules require `rgba` values to be defined using hexidecimal (`#AARRGGBB)`) not `rgba()` format.

   For example, the following rule:

   ```css
   .sidepane-row.attachment:hover{background-image:linear-gradient(180deg,#eee 0,#fbfbfb);background-repeat:repeat-x;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr="rgba(255, 238, 238, 0.93333)",endColorstr="rgba(255, 251, 251, 0.98431)",GradientType=0)}
   ```

   Should be written as:

   ```css
   .sidepane-row.attachment:hover{background-image:linear-gradient(180deg,#eee 0,#fbfbfb);background-repeat:repeat-x;filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#edffeeee,endColorstr=#fafffbfb,GradientType=0)}
   ```

   Notice the lack of quotes around the color values. You don't need them.

1. Configure your minifier to not reduce all rules down to a single line of CSS.

   This isn't really a great option because it doesn't address the two issues listed above, but it will prevent the ponyfill error.

It took long enough, but we finally got there. :)
