### ISSUE TITLE
CSS Parser Error

### ISSUE THREAD

**Issue by ccalamos** [jhildenbiddle/css-vars-ponyfill#97]
I noticed that the parser believes that nested elements such within the print page media query is invalid.

For instance

```css
@media print {
 @page {
  size: A4;
  margin: 10%;

  @bottom-left-corner {
    content: "Page " counter(page);
  }
 }
}
```

is valid CSS, however the parser throws a  Expected '}' error.
